# 18 Ablation Study Configurations
# Kernel × Channels × GRU = 2 × 3 × 3 = 18 models
# Run example:
#   python src/train.py --config configs/ablations_18.yaml --model all

data: data/connect4_10k_games.pt

# Kernel 3x3, Channels 16
k3_c16_gru8:
  kernel_size: 3
  cnn_channels: 16
  gru_hidden: 8
  batch_size: 81920
  epochs: 100
  lr: 0.001
  save_every: 1

k3_c16_gru32:
  kernel_size: 3
  cnn_channels: 16
  gru_hidden: 32
  batch_size: 8192
  epochs: 100
  lr: 0.001
  save_every: 1

k3_c16_gru128:
  kernel_size: 3
  cnn_channels: 16
  gru_hidden: 128
  batch_size: 64
  epochs: 100
  lr: 0.001
  save_every: 1

# Kernel 3x3, Channels 64
k3_c64_gru8:
  kernel_size: 3
  cnn_channels: 64
  gru_hidden: 8
  batch_size: 4096
  epochs: 100
  lr: 0.001
  save_every: 1

k3_c64_gru32:
  kernel_size: 3
  cnn_channels: 64
  gru_hidden: 32
  batch_size: 2048
  epochs: 100
  lr: 0.001
  save_every: 1

k3_c64_gru128:
  kernel_size: 3
  cnn_channels: 64
  gru_hidden: 128
  batch_size: 64
  epochs: 100
  lr: 0.001
  save_every: 1

# Kernel 3x3, Channels 256
k3_c256_gru8:
  kernel_size: 3
  cnn_channels: 256
  gru_hidden: 8
  batch_size: 1024
  epochs: 100
  lr: 0.001
  save_every: 1

k3_c256_gru32:
  kernel_size: 3
  cnn_channels: 256
  gru_hidden: 32
  batch_size: 512
  epochs: 100
  lr: 0.001
  save_every: 1

k3_c256_gru128:
  kernel_size: 3
  cnn_channels: 256
  gru_hidden: 128
  batch_size: 256
  epochs: 100
  lr: 0.001
  save_every: 1

# Kernel 6x6, Channels 16
k6_c16_gru8:
  kernel_size: 6
  cnn_channels: 16
  gru_hidden: 8
  batch_size: 8192
  epochs: 100
  lr: 0.001
  save_every: 1

k6_c16_gru32:
  kernel_size: 6
  cnn_channels: 16
  gru_hidden: 32
  batch_size: 8192
  epochs: 100
  lr: 0.001
  save_every: 1

k6_c16_gru128:
  kernel_size: 6
  cnn_channels: 16
  gru_hidden: 128
  batch_size: 64
  epochs: 100
  lr: 0.001
  save_every: 1

# Kernel 6x6, Channels 64
k6_c64_gru8:
  kernel_size: 6
  cnn_channels: 64
  gru_hidden: 8
  batch_size: 4096
  epochs: 100
  lr: 0.001
  save_every: 1

k6_c64_gru32:
  kernel_size: 6
  cnn_channels: 64
  gru_hidden: 32
  batch_size: 2048
  epochs: 100
  lr: 0.001
  save_every: 1

k6_c64_gru128:
  kernel_size: 6
  cnn_channels: 64
  gru_hidden: 128
  batch_size: 64
  epochs: 100
  lr: 0.001
  save_every: 1

# Kernel 6x6, Channels 256
k6_c256_gru8:
  kernel_size: 6
  cnn_channels: 256
  gru_hidden: 8
  batch_size: 512
  epochs: 100
  lr: 0.001
  save_every: 1

k6_c256_gru32:
  kernel_size: 6
  cnn_channels: 256
  gru_hidden: 32
  batch_size: 1024
  epochs: 100
  lr: 0.001
  save_every: 1

k6_c256_gru128:
  kernel_size: 6
  cnn_channels: 256
  gru_hidden: 128
  batch_size: 768
  epochs: 100
  lr: 0.001
  save_every: 1

# Convenience aggregate targets
k3_all:
  name: kernel3
  includes:
    - k3_c16_gru8
    - k3_c16_gru32
    - k3_c16_gru128
    - k3_c64_gru8
    - k3_c64_gru32
    - k3_c64_gru128
    - k3_c256_gru8
    - k3_c256_gru32
    - k3_c256_gru128

k6_all:
  name: kernel6

k6:
  includes:
    - k6_c16_gru8
    - k6_c16_gru32
    - k6_c16_gru128
    - k6_c64_gru8
    - k6_c64_gru32
    - k6_c64_gru128
    - k6_c256_gru8
    - k6_c256_gru32
    - k6_c256_gru128

all:
  name: ablations_all
  includes:
    - k3_all
    - k6_all

k6_c256:
  includes:
    - k6_c256_gru8
    - k6_c256_gru32
    - k6_c256_gru128
k3_gru_128:
  includes:
    - k3_c16_gru128
    - k3_c64_gru128
    - k3_c256_gru128

# Kernel 3x3 aggregate with weight decay applied to all 9 k3 models
k3_all_wd1e-4:
  name: kernel3_wd1e-4
  includes:
    - k3_c16_gru8
    - k3_c16_gru32
    - k3_c16_gru128
    - k3_c64_gru8
    - k3_c64_gru32
    - k3_c64_gru128
    - k3_c256_gru8
    - k3_c256_gru32
    - k3_c256_gru128
  weight_decay: 0.0001
