# Training configurations for different model sizes
# Run with: python src/train.py --config configs/train_configs.yaml --model small
# Override the dataset with --data if you want a different .pt file.

data: data/connect4_10k_games.pt

small:
  cnn_channels: [16, 64, 256]
  gru_hidden: 8
  batch_size: 64
  epochs: 100
  lr: 0.001
  save_every: 10

medium:
  cnn_channels: [16, 64, 256]
  gru_hidden: 32
  batch_size: 64
  epochs: 100
  lr: 0.001
  save_every: 10

large:
  cnn_channels: [16, 64, 256]
  gru_hidden: 128
  batch_size: 32  # Smaller batch for larger model
  epochs: 100
  lr: 0.001
  save_every: 10

# Aggregate profile that runs small, medium, and large sequentially
all:
  includes:
    - small
    - medium
    - large

# For quick testing
test:
  cnn_channels: [16, 64, 256]
  gru_hidden: 8
  batch_size: 32
  epochs: 20
  lr: 0.001
  save_every: 5
